version: '3.3'

services:
  db:
      image: 'mysql:${DB_VERSION}'
      volumes:
        - './data/mysql:/var/lib/mysql'
      ports:
        - 3308:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 400M
    ports:
      - '8080:80'
  wordpress:
    depends_on:
      - db
    image: 'wordpress:${WP_VERSION}'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./.env:/var/www/.env"
      - "./vendor:/var/www/vendor"
      - "./public:/var/www/html"
